### ISSUE TITLE
Benefits of g.connection

### ISSUE THREAD

**Issue by communitypediatrics** [pgjones/quart-db#11]
On the site [quart-db.readthedocs.io](https://quart-db.readthedocs.io/en/latest/discussion/per_connection.html), it says that g.connection is convenient for users. Is that because you don't need to write `async with app.db_pool.acquire() as connection: ...`? I don't see the benefits of having 1 new connection per request, and I don't find writing that `async with...` line to be so bad. Am I missing something?

**Comment by pgjones** [comment]
Yep, it is easier to use. Typically I find most routes use the DB so it makes sense (isn't wasteful). ~I intend to add an option to disable it soon.~ The option already exists, see `auto_request_connection`.

**Comment by communitypediatrics** [comment]
You're so clutch with these Python web frameworks.
