### ISSUE TITLE
global connection is not released on interrupted requests

### ISSUE THREAD

**Issue by catwell** [pgjones/quart-db#15]
I am not sure if I should open this bug here or on Quart. Here is the problem: when a request is interrupted by the client (resulting in HTTP 499 if you have nginx in front of Quart for instance) the `after_request_funcs` are not called in Quart, so `after_request` is not called in Quart-DB, so it leaks a connection. Ultimately the connection pool is saturated and Quart will stop processing requests (`acquire` will block).

To reproduce, create a route that returns megabytes of data, call it with cURL and kill cURL while it is running 10 times in a row. After that Quart should block.

A workaround is to disable `QUART_DB_AUTO_REQUEST_CONNECTION`.

**Comment by pgjones** [comment]
Should be fixed in 94a68e10b74176c966ff2741d68dcc42ea69a362

**Comment by catwell** [comment]
Thanks, I tried the fix and can confirm it works.
