### ISSUE TITLE
Return serial key value of inserted row 

### ISSUE THREAD

**Issue by VladimirVincan** [pgjones/quart-db#18]
Let's say I have the following table:

```sql
CREATE TABLE t (
  id SERIAL PRIMARY KEY,
  message VARCHAR(255)
);
```
I want to insert a new row. It could be done the following way:
```python
await g.connection.execute(
            """
            INSERT INTO t
            (message)
            VALUES
            ('some message')
            RETURNING Id;
            """)
```
I need to find which id was assigned to the new row. In psql, the returned values are:
```
 id 
----
  3
(1 row)

INSERT 0 1
```
But if I print the return values of the before-mentioned Python function, I only get `INSERT 0 1`.
How can I get the assigned id with quart-db?

**Comment by pgjones** [comment]
I think rather than `await g.connection.execute(` you need `await g.connection.fetch_val(`
