### ISSUE TITLE
PG: Backend options are passed into the TestBackend.connect

### ISSUE THREAD

**Issue by yeraydiazdiaz** [pgjones/quart-db#22]
Which are then forwarded into asyncpg connection which raises an error like:

> quart.testing.app.LifespanError: Error during startup connect() got an unexpected keyword argument 'min_size'

https://github.com/pgjones/quart-db/blob/abd22793a86b55b45ca8f2ba1be6f2eb3a2e77f9/src/quart_db/backends/asyncpg.py#L198

**Comment by pgjones** [comment]
Fixed in 24d625f6ddb7633d0c17465d67bdebfc5c74d9a5
