### ISSUE TITLE
Can't call Postgres Functions that return jsonb payloads

### ISSUE THREAD

**Issue by bradleyf** [pgjones/quart-db#23]
This may apply to any postgres functions.   I am calling particular ones that return jsonb payloads.

result = await g.connection.execute(
   query="SELECT * FROM public.my_function(:a, :b, :c)",
   values={"a":"foo", "b":"bar","c": 99}
)

result returns "SELECT 1"

Please advise

**Comment by pgjones** [comment]
I think this might depend on your function as `await g.connection.fetch_val("""select '{"a":"b"}'::jsonb""")` works as expected for me.
