### ISSUE TITLE
quart-db vs sqlalchemy ?

### ISSUE THREAD

**Issue by copdips** [pgjones/quart-db#24]
Hello,

Could you please provide some information about quart-db vs sqlalchemy ?
Thanks

**Comment by pgjones** [comment]
Quart-DB is specifically designed to be used with Quart, it is a Quart extension that sets up DB connections and places a connection on the `g` object. SQLAlchemy can be used with Quart or anything else. You could use SQLAlchemy to reimplement Quart-DB if desired.

**Comment by Beetroit** [comment]
Does quart db work as an ORM, like provides `add`, `commit` etc?, the way sqlalchemy does.
