### ISSUE TITLE
Ensure only a singular background migration is concurrent

### ISSUE THREAD

**Issue by pgjones** [pgjones/quart-db#27]
If there are multiple Quart workers for example

**Comment by larsblumberg** [comment]
I just ran into this issue when I scaled my backend to 2 instances and then deployed: as both instances applied the migration I had one instance failing with `MigrationFailedError: Database is ahead of local migrations` as a consequence of parallel migrations.

I am happy to contribute a fix for this. What's the best way forward to tackle this problem?

Maybe a new column in table `schema_migration` which indicates that a migration is currently being applied while making sure that the row is locked for the moment of reading + updating that value?

**Comment by pgjones** [comment]
I think `MigrationFailedError: Database is ahead of local migrations` could only have happened if your existing code restarted after your new code had applied the new migration.

I don't think it is possible for Quart-DB to ensure this (as background tasks cannot run in a transaction and hence can't take affective DB locks). I've improved the documentation in ba1128013fe0b63b4871c945a39375201eeb672b

**Comment by larsblumberg** [comment]
This is what happened:

1. deployed a new backend service version which came with a db migration
2. as there’s horizontal scaling enabled, two instances where deployed in parallel, which is an unfortunate decision by Digital Ocean App Platform
3. the upgrade migrations ran in parallel which led to an SQL error (tried to add an already existing column)
4. service fails, deployment thus fails
5. Digital Ocean App Platform performs a roll back, which likely restarts the service (as you say)

Is there a chance that the migration could simply lock the schema migration row while performing the migration? This way another instance (or worker) would wait for the row until it’s unlocked and only then read the schema migration version, locking the row this time itself.

> I don't think it is possible for Quart-DB to ensure this (as background tasks cannot run in a transaction and hence can't take affective DB locks).

I’m not properly understanding here: Are you saying background tasks can’t use a DB transaction? Why is that?

Would the solution be to run the migration in a foreground tasks? Isn’t that better anyway given that we don’t want the web server (Quart/hypercorn) to start taking requests as long as migrations are executed?

I might be misunderstanding something here.

**Comment by pgjones** [comment]
> Is there a chance that the migration could simply lock the schema migration row while performing the migration?

Yes, this is what Quart-DB does for foreground migrations.

> Are you saying background tasks can’t use a DB transaction? Why is that?

Yes, as they typically for long running and would lock the database for too long a period.

> Would the solution be to run the migration in a foreground tasks?

Yes, I think so.

**Comment by larsblumberg** [comment]
I do realize now that this issue talks about background migrations, I haven't paid attention to this. I am actually exclusively using foreground migrations, haven't added background migration functions yet.

So I do wonder now why I did run into a migration failure and a subsequent deployment rollback. I was  probably under the wrong assumption that the same migration had been applied in parallel by multiple server instances, but as you are saying row locking already does takes place for foreground migrations. So we consider my case obsolete now, I am sorry for the noise! And thank you once more for your great libraries, I really like them for their simplicity, I regularly read their code internals to better understand certain mechanisms. It's very easy to follow.

**Comment by pgjones** [comment]
Yep, that is how Quart-DB works at the moment if you use `migrate`.

**Comment by larsblumberg** [comment]
Hi @pgjones, after I realized that this issue is about background migrations, which have to be explicitly enabled in each migration file, I had edited and rewritten my entire post above :-)
