### ISSUE TITLE
Insert Values

### ISSUE THREAD

**Issue by mkatkov** [pgjones/quart-db#28]
Apparently, the code does not accept an array of values ( https://github.com/pgjones/quart-db/blob/main/src/quart_db/backends/asyncpg.py ln 150 return render(query, **(values or {}))),whereas buildpg assume an array as an input 
https://github.com/samuelcolvin/buildpg/blob/master/tests/test_query.py lns. 55-74.

**Comment by pgjones** [comment]
Should be fixed in e624a9ff8c66b4c2b0372754bb05feed59e88e20
