### ISSUE TITLE
Why was `buildpg` prefered over `databases` for named parameter binding?

### ISSUE THREAD

**Issue by larsblumberg** [pgjones/quart-db#3]
Hi Philip,

in [this blog post](https://pgjones.dev/blog/quart-postgres-2021/) you endorse the [`databases` library](https://github.com/encode/databases) which allows for named parameter binding. When reading the [dependencies](https://github.com/pgjones/quart-db/blob/00e89700ee51753e9176a2653b3ba36aa97ff970/pyproject.toml) and [documentation](https://github.com/pgjones/quart-db/blob/e41747fcac601de0235f91cd4725265481ed926b/docs/how_to_guides/bind_parameters.rst) of `Quart-DB` I however find references tk [this other library called `buildpg`](https://github.com/samuelcolvin/buildpg).

Now that I am very eager to integrate `Quart-DB` into my app I'd like to learn why why you favored `buildpg` over `databases`. Could you please share some light?

PS: Thank you for your wonderful work. It hits my taste a lot!

**Comment by larsblumberg** [comment]
Closing, b/c as per README you prefer a message on gitter. Will post there.

**Comment by pgjones** [comment]
See, https://quart-db.readthedocs.io/en/latest/discussion/databases.html
